name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - name: Log in to OCI Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.OCI_REGISTRY_URL }}
          username: ${{ secrets.OCI_REGISTRY_USER }}
          password: ${{ secrets.OCI_REGISTRY_TOKEN }}

      - name: Package and push Helm chart
        run: |
          helm package . --app-version ${{ github.sha }} --version 0.1.${{ github.run_number }}
          helm push paperless-ai-0.1.${{ github.run_number }}.tgz oci://${{ secrets.OCI_REGISTRY_URL }}/paperless-ai
        working-directory: .
