name: Publish Helm Chart

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package Helm Chart
        run: |
          helm package .
          echo "CHART_PACKAGE=$(ls *.tgz)" >> $GITHUB_ENV

      - name: Log in to OCI Registry
        run: |
          echo "${{ secrets.OCI_REGISTRY_TOKEN }}" | helm registry login ${{ secrets.OCI_REGISTRY_URL }} \
            --username "${{ secrets.OCI_REGISTRY_USER }}" \
            --password-stdin

      - name: Push Helm Chart to OCI Registry
        run: |
          helm push ${{ env.CHART_PACKAGE }} oci://${{ secrets.OCI_REGISTRY_URL }}/library

      - name: Log out of OCI Registry
        if: always()
        run: helm registry logout ${{ secrets.OCI_REGISTRY_URL }}
